version: '3.8'

services:
  web-server:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  db-server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
